---
title: "EDA"
author: "Hunter Gregory"
date: "4/5/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data = read.csv("debates_2020_updated.csv")
```


```{r fixing-data-input}
data['candidate'] = ifelse(data['candidate'] == "True", TRUE, FALSE)[,1]
data['X'] <- data['X'] + 1 # readjusting for r indexing
```

```{r creating-document-separation}
doc_starts <- data$X[data$candidate]
doc_list <- c()
curr_doc <- ""
curr_bool <- FALSE
for (i in 1:dim(data)[1]){
  if (!curr_bool == data$candidate[i]){
    doc_list <- c(doc_list, curr_doc)
    curr_bool <- !curr_bool
    curr_doc <- ""
  }
  curr_doc <- paste(curr_doc, data$preprocessed_speech[i])
}
doc_list <- c(doc_list, curr_doc)
char_lengths = nchar(doc_list)
if (sort(unique(char_lengths))[1] == 0)
  print("WARNING: some docs have length 0")
```


```{r}
unique(data$debate_section)
```

```{r}
for (sect in unique(data$debate_section)) {
  indices = data$debate_section == sect
  print("SECTION NAME and SPEECH COUNT")
  print(sprintf("%s speeches %s", sum(indices), sect))
  print("DEBATE NAMES")
  print(as.character(unique(data$debate_name[indices])))
  print("")
}
```

## TODO
- number of speeches for each debate and for each section in debate (walk through debate by debate)
- most frequent words used



